### PR TITLE
Add/GitHub actions

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

I add [github-actions](https://docs.github.com/en/actions) and [dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) for github-actions. I hope it is useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by PascalCorpsman** [comment]
Hello,
you let run a different code formater over the code, this explains the huge amount of changes in the files.
Please revert that so that it can be seen what you actually changed.

**Comment by theavege** [comment]
@PascalCorpsman I've done

**Comment by PascalCorpsman** [comment]
Ok, lets see whats the outcome of: https://github.com/PascalCorpsman/sandtris/issues/3 before i decide to merge the PR..

**Comment by theavege** [comment]
@PascalCorpsman What do you decide?

**Comment by PascalCorpsman** [comment]
i am still in decicion making progress, started now with the testapp, next step is integrating all this into the setup-lazarus thing, so it will take some time to come to a solution..

**Comment by PascalCorpsman** [comment]
Sorry your PR does not meet the plans i have with this repository.

**Pull request closed without merging**
